global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Bugsink metrics (if you expose a /metrics endpoint later)
  - job_name: 'bugsink'
    static_configs:
      - targets: ['bugsink:8000']
